---
secretName: devstack
configMap:
  ceilometer:
    dbUri: "sqlite:///:memory:"
  horizon:
    ingress:
      host: "horizon.vexxhost.com"
  keystone:
    configDir: /etc/keystone
  heat:
    configDir: /etc/heat
  chronyd: {}