---
secretName: devstack
configMap:
  ceilometer:
    dbUri: "sqlite:///:memory:"
  glance:
    configDir: /etc/glance
    dataDir: /opt/stack/data/glance
  horizon:
    ingress:
      host: "horizon.vexxhost.com"
  keystone:
    configDir: /etc/keystone
  heat:
    configDir: /etc/heat
  magnum:
    configDir: /etc/magnum
  chronyd: {}
