- hosts: all
  roles:
    - role: helm-template
      vars:
        helm_release_name: openstack-operator
        helm_chart: ./chart
  tasks:
    # TODO(mnaser): Generate all manifests and ensure git is not dirty
    - include_tasks: tests/memcached.yaml
    - include_tasks: tests/rabbitmq.yaml

- import_playbook: devstack.yaml