---
# Copyright (c) 2020 VEXXHOST, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Configure the clusterrole for storage-provisioner
  shell: |
    kubectl patch clusterrole -n kube-system system:persistent-volume-provisioner --type='json' \
    -p='[{"op": "add", "path": "/rules/0", "value": {"apiGroups": [""], "resources":["endpoints"], "verbs":["get", "list", "create", "update"]}}]'

- name: Remove the default storage-provisioner
  shell: |
    kubectl delete po -n kube-system storage-provisioner

- name: Deploy the latest storage-provisioner
  shell: |
    cat <<EOF | kubectl apply -f-
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: storage-provisioner
      namespace: kube-system
      labels:
        integration-test: storage-provisioner
        addonmanager.kubernetes.io/mode: Reconcile
    spec:
      serviceAccountName: storage-provisioner
      hostNetwork: true
      containers:
      - name: storage-provisioner
        image: gcr.io/k8s-minikube/storage-provisioner:latest
        command: ["/storage-provisioner"]
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      volumes:
      - name: tmp
        hostPath:
          path: /tmp
          type: Directory
    EOF