- secret:
    name: openstack-operator-dockerhub
    data:
      username: vexxhostzuul
      password: !encrypted/pkcs1-oaep
        - JgslylmR4+iQxQBEa05Mx7FJjjjeM+Oqu60N7pxGA32vQkTMRHfGgXz9HXz1A8XAEesQM
          ZPSWhpiEBDhzyugOTJBPl4Ha/4xBVv6fL1ikxOPeVNW4PU9tVbi6MMkdsYkF40lGl5ejz
          TWprQDWD5ATdwz79IOjgwnEuZFA9Y0+g7jMyGUjg5deoaaubVgtvLHan58LznUZpmGHcM
          NjRWvNRJBzb2Siwv+B2phFIYy4yXxMC3HSXbspTklX/oQsmdTGgfTZ+rW7/hwyfyuoxfG
          QBsVU3JCjzlLZaxmy64jYoOna2M33+Vibc2C1WCiYtbBzunvrQxT9cvdNJXySTxeTJ6PL
          5KGVToep1O5PMuNdk9MonVAmbkWpf/Leg81Az02+9tJUNKOrzUxnf8iwHva2+iPbrNAEe
          wVKBqvOkBPKZjBJtY73Db2r6if/MGc7H1wkHd5s1UJoHU5soObJAYgksea6sC7OVv3XYp
          UhSE17snurne0HAZRqhQ/JR6c1ipYMKCfj0D4tyJH9ZBW6faB1P/H2A8f22mRJW576aQI
          Q9/HpF3PmAJwbmrlZKyE/jBKUlte27JGZZ307i74Yu9pA2/bVKF6ynpT3sRShLLYDpG6A
          AyoJYUA7yRyHhNRHcOX7ZrvOhMCbTPJOqiMaDamNRkJAJWw6GW25S1n5onXjxc=

- job:
    name: openstack-operator:images:build
    parent: opendev-build-docker-image
    provides: openstack-operator:image:operator
    vars: &openstack_operator_images
      docker_images:
        - context: images/mcrouter
          repository: vexxhost/mcrouter
        - context: images/mcrouter_exporter
          repository: vexxhost/mcrouter_exporter
        - context: images/memcached
          repository: vexxhost/memcached
        - context: images/memcached_exporter
          repository: vexxhost/memcached_exporter
        - context: .
          repository: vexxhost/openstack-operator

- job:
    name: openstack-operator:images:upload
    parent: opendev-upload-docker-image
    provides: openstack-operator:image:operator
    vars: *openstack_operator_images
    secrets:
      - name: docker_credentials
        secret: openstack-operator-dockerhub
        pass-to-parent: true

- job:
    name: openstack-operator:images:promote
    parent: opendev-promote-docker-image
    vars: *openstack_operator_images
    secrets:
      - name: docker_credentials
        secret: openstack-operator-dockerhub
        pass-to-parent: true

- job:
    name: openstack-operator:linters:chart
    parent: chart-testing-lint
    vars:
      zuul_work_dir: "{{ zuul.project.src_dir }}/chart"

- job:
    name: openstack-operator:functional
    parent: devstack-tempest
    requires:
      - openstack-operator:images
    pre-run: playbooks/functional/pre.yaml
    run: playbooks/functional/run.yaml
    post-run: playbooks/functional/post.yaml
    vars:
      devstack_services:
        etcd3: false
      docker_use_buildset_registry: true
      minikube_dns_resolvers: ['1.1.1.1', '8.8.8.8']

- project:
    check:
      jobs:
        - openstack-operator:linters:chart
        - openstack-operator:images:build
        - openstack-operator:functional:
            dependencies:
              - openstack-operator:images:build
    gate:
      jobs:
        - openstack-operator:linters:chart
        - openstack-operator:images:upload
        - openstack-operator:functional:
            dependencies:
              - openstack-operator:images:upload
    promote:
      jobs:
        - openstack-operator:images:promote