- job:
    name: openstack-operator:images:build
    parent: vexxhost-build-docker-image
    provides: openstack-operator:image:operator
    vars: &openstack_operator_images
      docker_images:
        - context: images/mcrouter
          repository: vexxhost/mcrouter
        - context: images/mcrouter_exporter
          repository: vexxhost/mcrouter_exporter
        - context: images/memcached
          repository: vexxhost/memcached
        - context: images/memcached_exporter
          repository: vexxhost/memcached_exporter
        - context: images/rabbitmq
          repository: vexxhost/rabbitmq
        - context: .
          repository: vexxhost/openstack-operator

- job:
    name: openstack-operator:images:upload
    parent: vexxhost-upload-docker-image
    provides: openstack-operator:image:operator
    vars: *openstack_operator_images

- job:
    name: openstack-operator:images:promote
    parent: vexxhost-promote-docker-image
    vars: *openstack_operator_images

- job:
    name: openstack-operator:linters:chart
    parent: chart-testing-lint
    vars:
      zuul_work_dir: "{{ zuul.project.src_dir }}/chart"

- job:
    name: openstack-operator:functional
    parent: devstack-tempest
    requires:
      - openstack-operator:images
    pre-run: playbooks/functional/pre.yaml
    run: playbooks/functional/run.yaml
    post-run: playbooks/functional/post.yaml
    vars:
      devstack_services:
        etcd3: false
      docker_use_buildset_registry: true
      minikube_dns_resolvers: ['1.1.1.1', '8.8.8.8']

- project:
    check:
      jobs:
        - golangci-lint
        - openstack-operator:linters:chart
        - openstack-operator:images:build
        - openstack-operator:functional:
            dependencies:
              - openstack-operator:images:build
    gate:
      jobs:
        - golangci-lint
        - openstack-operator:linters:chart
        - openstack-operator:images:upload
        - openstack-operator:functional:
            dependencies:
              - openstack-operator:images:upload
    promote:
      jobs:
        - openstack-operator:images:promote