apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: operator-config
  labels:
{{ include "openstack-operator.labels" . | indent 4 }}
data:
{{- with .Values.configMap }}
  operator-config.yaml: |
{{ toYaml . | indent 4 }}
{{- end }}
