---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "openstack-operator.fullname" . }}
  labels:
{{ include "openstack-operator.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
{{ include "openstack-operator.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "openstack-operator.labels" $ | indent 8 }}
    spec:
      serviceAccountName: {{ include "openstack-operator.fullname" . }}
      terminationGracePeriodSeconds: 10
      containers:
      - name: operator
        image: vexxhost/openstack-operator:latest
        command: ["/usr/local/bin/kopf"]
{{- with .Values.secretName }}
        envFrom:
        - secretRef:
            name: {{ . }}
{{- end }}
        args:
        - run
        - -m
        - openstack_operator.horizon
        - -m
        - openstack_operator.mcrouter
        - -m
        - openstack_operator.memcached
        - -m
        - openstack_operator.openstack.identity.services
        - -m
        - openstack_operator.rabbitmq
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
