---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "openstack-operator.fullname" . }}
  labels:
{{ include "openstack-operator.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
{{ include "openstack-operator.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "openstack-operator.labels" $ | indent 8 }}
    spec:
      serviceAccountName: {{ include "openstack-operator.fullname" . }}
      terminationGracePeriodSeconds: 10
      containers:
      - name: operator
        image: vexxhost/openstack-operator:latest
        command: ["/usr/local/bin/kopf"]
        args:
        - run
        - -m
        - openstack_operator.memcached
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      - name: go-operator
        image: vexxhost/openstack-operator:latest
        command: ["/manager"]
        args:
        - --enable-leader-election
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
