#!/usr/local/bin/python
# Copyright (c) 2020 VEXXHOST, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import pkg_resources

import sentry_sdk
from sentry_sdk.integrations.sqlalchemy import SqlalchemyIntegration

from heat.httpd.heat_api import init_application
from sentry_sdk.integrations import wsgi

VERSION = pkg_resources.get_distribution("openstack-heat").version

sentry_sdk.init(
    release="heat@%s" % VERSION,
    integrations=[SqlalchemyIntegration()]
)

application = init_application()
application = wsgi.SentryWsgiMiddleware(application)
