---
apiVersion: identity.openstack.org/v1alpha1
kind: Keystone
metadata:
  name: sample
spec:
  configDir: /etc/keystone
  ingress:
  - host: "keystone1.vexxhost.com"
  - host: "keystone2.vexxhost.com"
