apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-config
data:
  operator-config.yaml: |
    ceilometer:
      dbUri: "sqlite:///:memory:"
    horizon:
      ingress:
        host: "horizon.vexxhost.com"
    keystone: {}
    heat:
      configDir: /etc/heat
      ingress:
        host:
          api: "h-api.vexxhost.com"
          api-cfn: "h-api-cfn.vexxhost.com"
    magnum:
      configDir: /etc/magnum
    chronyd: {}
