apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-config
data:
  operator-config.yaml: |
    ceilometer:
      dbUri: "sqlite:///:memory:"
    horizon:
      ingress:
        host: "horizon.vexxhost.com"
    keystone: {}
    heat: {}
    magnum: {}
    glance:
      dataDir: /opt/stack/data/glance
    chronyd: {}
