apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-config
data:
  operator-config.yaml: |
    barbican: {}
    ceilometer:
      dbUri: "sqlite:///:memory:"
    horizon:
      ingress:
        host: "horizon.vexxhost.com"
    keystone: {}
    heat: {}
    magnum: {}
    chronyd: {}
    placement: {}
    backup:
      secretName: aws-backup
      url: s3://backups/
    glance: {}
