#!/usr/local/bin/python
# Copyright (c) 2020 VEXXHOST, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import pkg_resources

import sentry_sdk

from glance.common.wsgi_app import init_app
from sentry_sdk.integrations import wsgi

VERSION = pkg_resources.get_distribution("glance").version

sentry_sdk.init(
    release="glance@%s" % VERSION,
    traces_sample_rate=0.1
)

application = init_app()
application = wsgi.SentryWsgiMiddleware(application)
