---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: applicationcredentials.identity.openstack.org
spec:
  group: identity.openstack.org
  names:
    kind: ApplicationCredential
    listKind: ApplicationCredentialList
    plural: applicationcredentials
    singular: applicationcredential
  scope: Cluster
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
