---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: heats.orchestration.openstack.org
spec:
  group: orchestration.openstack.org
  names:
    kind: Heat
    listKind: HeatList
    plural: heats
    singular: heat
  scope: Namespaced
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
